behaviors:
  1v1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 1.0e-5
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9954
        strength: 1.0
    checkpoint_interval: 5000000
    max_steps: 5000000
    time_horizon: 2048
    summary_freq: 50000
    self_play:
      save_steps: 60000
      team_change: 360000
      swap_steps: 30000
      window: 10
      play_against_latest_model_ratio: 0.6
